const API=window.PARTSHUB_CONFIG.apiBaseUrl;const readCart=()=>{try{return JSON.parse(localStorage.getItem('partshub-cart-v4')||'{}')}catch{return {}}};const state={products:[],shown:[],cart:readCart(),active:null};const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n||0);const escape=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function imageTag(url,alt){return `<img src="${escape(url||'')}" alt="${escape(alt)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="fallback" style="display:none">⚙</span>`}
async function load(){try{const r=await fetch(`${API}/products`);if(!r.ok)throw new Error(`API ${r.status}`);const data=await r.json();state.products=data.items;state.shown=[...state.products];render()}catch(e){$('#productGrid').innerHTML=`<div class="error"><b>無法連線後端 API</b><br>${escape(e.message)}<br>請確認 backend 已在 8000 port 啟動，且 frontend/config.js 的 apiBaseUrl 正確。</div>`}}
function card(p){return `<article class="card"><div class="card-image" data-detail="${p.id}">${imageTag(p.primary_image,p.name_zh)}<span class="image-count">相簿 ${p.gallery.length} 張</span><span class="diagram-pill">圖號 ${escape(p.diagram_no)}</span></div><div class="card-body"><span class="english">${escape(p.name_en)}</span><h3>${escape(p.name_zh)}</h3><code class="part">${escape(p.part_number)}</code><p class="desc">${escape(p.description_zh)}</p><div class="price-row"><strong>${money(p.price_twd)}</strong>${p.msrp_twd?`<del>原價 ${money(p.msrp_twd)}</del>`:''}</div><div class="card-actions"><button class="detail-btn" data-detail="${p.id}">查看相簿</button><button class="add-btn" data-add="${p.id}">加入購物車</button></div></div></article>`}
function render(){let a=[...state.shown];const s=$('#sortSelect').value;if(s==='price-asc')a.sort((x,y)=>x.price_twd-y.price_twd);if(s==='price-desc')a.sort((x,y)=>y.price_twd-x.price_twd);if(s==='diagram')a.sort((x,y)=>Number(x.diagram_no)-Number(y.diagram_no)||x.id-y.id);$('#productGrid').innerHTML=a.map(card).join('');$('#resultCount').textContent=`共 ${a.length} 項零件`;bind();renderCart()}
function bind(){document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>openDetail(Number(x.dataset.detail)));document.querySelectorAll('[data-add]').forEach(x=>x.onclick=e=>{e.stopPropagation();add(Number(x.dataset.add))})}
function openDetail(id){const p=state.products.find(x=>x.id===id);state.active=p;$('#modalName').textContent=p.name_zh;$('#modalPart').textContent=p.part_number;$('#modalDescription').textContent=p.description_zh;$('#modalYears').textContent=p.years||'請依 VIN 核對';$('#modalOther').textContent=p.other_names||'—';$('#modalReplaces').textContent=p.replaces||'—';$('#modalPrice').textContent=money(p.price_twd);$('#modalMsrp').textContent=p.msrp_twd?`原價 ${money(p.msrp_twd)}`:'';$('#modalDiagram').textContent=`原廠圖號 ${p.diagram_no}・相簿 ${p.gallery.length} 張`;$('#sourceLink').href=p.source_url;$('#modalAdd').onclick=()=>add(p.id);setMain(p.gallery[0],0);$('#thumbnailList').innerHTML=p.gallery.map((im,i)=>`<button class="thumb ${i===0?'active':''}" data-thumb="${i}" title="${escape(im.label_zh)}">${imageTag(im.source_url,im.label_zh)}</button>`).join('');document.querySelectorAll('[data-thumb]').forEach(x=>x.onclick=()=>setMain(p.gallery[Number(x.dataset.thumb)],Number(x.dataset.thumb)));$('#modalBackdrop').classList.remove('hidden');document.body.style.overflow='hidden'}
function setMain(im,i){$('#modalMainImage').src=im.source_url;$('#modalMainImage').style.display='block';$('#imageBadge').textContent=im.label_zh;document.querySelectorAll('.thumb').forEach((x,n)=>x.classList.toggle('active',n===i))}
function closeDetail(){$('#modalBackdrop').classList.add('hidden');document.body.style.overflow=''}
function add(id){state.cart[id]=(state.cart[id]||0)+1;save();toast('已加入購物車')}
function save(){try{localStorage.setItem('partshub-cart-v4',JSON.stringify(state.cart))}catch{}renderCart()}
function change(id,d){state.cart[id]=(state.cart[id]||0)+d;if(state.cart[id]<=0)delete state.cart[id];save()}
function renderCart(){const entries=Object.entries(state.cart);$('#cartCount').textContent=entries.reduce((a,[,q])=>a+q,0);let subtotal=0;$('#cartItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=state.products.find(x=>x.id===Number(id));if(!p)return'';subtotal+=p.price_twd*q;return `<div class="cart-line">${imageTag(p.primary_image,p.name_zh)}<div><h4>${escape(p.name_zh)}</h4><small>${money(p.price_twd)}</small><div class="qty"><button onclick="change(${id},-1)">−</button><span>${q}</span><button onclick="change(${id},1)">＋</button></div></div><b>${money(p.price_twd*q)}</b></div>`}).join(''):'<p style="padding:22px;color:#61718a">購物車目前是空的</p>';const shipping=subtotal===0?0:(subtotal>=3000?0:120);$('#subtotal').textContent=money(subtotal);$('#shipping').textContent=shipping?money(shipping):'免運';$('#total').textContent=money(subtotal+shipping)}
function openCart(){$('#cartDrawer').classList.add('open');$('#drawerShade').classList.remove('hidden')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerShade').classList.add('hidden')}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
async function checkout(){const items=Object.entries(state.cart).map(([product_id,quantity])=>({product_id:Number(product_id),quantity}));if(!items.length)return toast('購物車是空的');try{const r=await fetch(`${API}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'建立訂單失敗');state.cart={};save();closeCart();toast(`訂單 ${d.order_number} 已建立`)}catch(e){toast(e.message)}}
$('#searchInput').oninput=e=>{const q=e.target.value.trim().toLowerCase();state.shown=state.products.filter(p=>`${p.name_zh} ${p.name_en} ${p.part_number}`.toLowerCase().includes(q));render()};$('#sortSelect').onchange=render;$('#modalClose').onclick=closeDetail;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeDetail()};$('#cartButton').onclick=openCart;$('#cartClose').onclick=closeCart;$('#drawerShade').onclick=closeCart;$('#checkoutButton').onclick=checkout;load();
